Repository baltic-guys/read-path, pull requests merged in 2020-05, with the labels that each got.

#13 Added controllers using a stub
  backend/Dockerfile
  backend/src/main/kotlin/com/baltic/road/path/app/config/DaoConfig.kt
  backend/src/main/kotlin/com/baltic/road/path/app/controllers/BookController.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/BookDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/impl/InMemoryBookDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/BookDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/services/BookService.kt
  backend/src/main/kotlin/com/baltic/road/path/app/services/BookServiceImpl.kt
  baltic-frontend/Dockerfile
  baltic-frontend/src/App.tsx
  docker-compose.yaml
  nginx/Dockerfile
  nginx/conf
Labels: enhancement

#12 Simple auth
  .gitignore
  backend/build.gradle.kts
  backend/src/main/kotlin/com/baltic/road/path/app/config/AuthConfig.kt
  backend/src/main/kotlin/com/baltic/road/path/app/config/DaoConfig.kt
  backend/src/main/kotlin/com/baltic/road/path/app/config/SwaggerConfig.kt
  backend/src/main/kotlin/com/baltic/road/path/app/controllers/AuthController.kt
  backend/src/main/kotlin/com/baltic/road/path/app/controllers/PlaygroundController.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/SessionDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/UserDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/impl/InMemorySessionDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/impl/InMemoryUserDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/AuthDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/SessionDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/TestDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/UserDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/AuthService.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/CredentialService.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/impl/CredentialServiceImpl.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/impl/SimpleAuthServiceImpl.kt
  backend/src/main/resources/application.yaml
  baltic-frontend/src/App.test.tsx
  baltic-frontend/src/App.tsx
  baltic-frontend/src/AppAuth.tsx
  baltic-frontend/src/Login.tsx
  baltic-frontend/src/index.tsx
  baltic-frontend/yarn.lock
  build.gradle.kts
Labels: enhancement

#19 Linters
  backend/build.gradle.kts
  backend/src/main/kotlin/com/baltic/road/path/app/RoadPathApplication.kt
  backend/src/main/kotlin/com/baltic/road/path/app/config/AuthConfig.kt
  backend/src/main/kotlin/com/baltic/road/path/app/config/DaoConfig.kt
  backend/src/main/kotlin/com/baltic/road/path/app/config/SwaggerConfig.kt
  backend/src/main/kotlin/com/baltic/road/path/app/controllers/AuthController.kt
  backend/src/main/kotlin/com/baltic/road/path/app/controllers/BookController.kt
  backend/src/main/kotlin/com/baltic/road/path/app/controllers/PlaygroundController.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/BookDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/SessionDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/UserDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/impl/InMemoryBookDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/impl/InMemorySessionDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/impl/InMemoryUserDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/AuthDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/BookDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/SessionDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/TestDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dto/UserDto.kt
  backend/src/main/kotlin/com/baltic/road/path/app/gr/SimpleGRClient.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/AuthService.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/BookService.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/CredentialService.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/impl/BookServiceImpl.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/impl/CredentialServiceImpl.kt
  backend/src/main/kotlin/com/baltic/road/path/app/service/impl/SimpleAuthServiceImpl.kt
  build.gradle.kts
  detekt.yml
Labels: feature, major

#22 crud tests
  .github/workflows/gradle.yml
  backend/build.gradle.kts
  backend/src/main/kotlin/com/baltic/road/path/app/dao/BookDao.kt
  backend/src/main/kotlin/com/baltic/road/path/app/dao/impl/InMemoryBookDao.kt
  backend/src/test/java/com/baltic/road/path/app/extensions/Book.java
  backend/src/test/java/com/baltic/road/path/app/extensions/BookEx.java
  backend/src/test/java/com/baltic/road/path/app/unit/CrudTest.java
  backend/src/test/resources/application.yaml
Labels: major, testing
